/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Demo Express API
 * API documentation for the Demo Express project
 * OpenAPI spec version: 1.0.0
 */

export type LoginRequestUser = {
  email: string;
  password: string;
};
