/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Store
 * OpenAPI spec version: 1.0.0
 */

export interface User {
  id?: number;
  email?: string;
  created_at?: string;
  updated_at?: string;
}
